version: "3.8"

services:
  mysql-blog:
    image: mysql:8
    container_name: mysql-blog
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Blog_benchmark_MySQL
    volumes:
      - "./container-mysql/data:/var/lib/mysql"
      - "./container-mysql/conf.d:/etc/mysql/conf.d"
      - "./sql:/docker-entrypoint-initdb.d"
    networks:
      - blog-network
  blog:
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: blog
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-blog:3306/apitrail?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Blog_benchmark_MySQL
    ports:
      - 8082:8080
    networks:
      - blog-network
    depends_on:
      - mysql-blog

networks:
  blog-network:
    name: blog-network
