version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql-blog
    ports:
      - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "./sql:/docker-entrypoint-initdb.d"
    networks:
      - blog-network
  blog:
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: blog
    ports:
      - "8080:8080"
    networks:
      - blog-network
    depends_on:
      - mysql

networks:
  blog-network:
    name: blog-network
