from zhipuai import ZhipuAI
import os
import messages.initMessage as initMessage
import sendRequests

# init the zhipuAI client
key = os.environ.get('ZHIPUAI_APIKEY')
client = ZhipuAI(api_key = key)


# send requests generated by zhipuAI and get the response
testCasesCount = 1
while True:
    print(f"Test Case {testCasesCount}:")
    testCasesCount += 1
    # init the messages
    _messages = []
    _initmessage = initMessage.getMessage("E:\\y1\\api test\\code\\requests-send\\swagger_blog.txt")
    _messages.append({"role": "user", "content": _initmessage})
    while True:   
        response = client.chat.completions.create(
            model = "glm-4",
            messages = _messages
        )

        answer = response.choices[0].message.content
        _messages.append({"role": "assistant", "content": answer})
        if(answer == 'end'):
            print("OVER!")
            break
        print(f'ZhipuAI: {answer}')
        request_response = sendRequests.send(answer)
        _messages.append({"role": "user", "content": request_response})
        print(f'USER: {request_response}')
